name: GaldreenBlocksUnlimited
version: '${project.version}'
main: de.ewu2000.galdreenblocksunlimited.GaldreenBlocksUnlimited
api-version: 1.19
description: Adds custom Blocks
commands:
  CreateGaldreenBlock:
    description: Creates a Galdreen Block
    usage: /createGaldreenBlock <Coord-X> <Coord-Y> <Coord-Z> <useNameBool> <Name> !!Hold Material in hand!!
    permission: op
  GiveAllGaldreenBlocks:
    description: Gives the executing Player all of the GaldreenBlocks
    usage: /giveAllGaldreenBlocks
  AddPlaceable:
    description: Adds a block to the list of blocks that can be placed in non vanilla locations.
    usage: /addPlaceable !!Hold Item in hand!!
    permission: op
